.include "m8515def.inc"

.org $00
	rjmp RESET
.org $07
	rjmp ISR_TOV0
.def counter = r20
.def pattern = r26


RESET:
	ldi	r16,low(RAMEND)
	out	SPL,r16	            ;init Stack Pointer		
	ldi	r16,high(RAMEND)
	out	SPH,r16
	
	ldi counter, 8
	ldi pattern, 0b11111111
	ldi r16, (1<<CS01)|(1<<CS00)	; 
	out TCCR0,r16			
	ldi r16,1<<TOV0
	out TIFR,r16		; Interrupt if overflow occurs in T/C0
	ldi r16,1<<TOIE0
	out TIMSK,r16		; Enable Timer/Counter0 Overflow int
	ldi r16, 0b11111111
	out DDRC,r16		; Set port C as output
	ldi r16, 0
	out PORTC, r16
	mov r16, pattern
	out PORTC, r16
	sei

forever:
	rjmp forever

ISR_TOV0:
	dec counter
	breq MAU_UBAH_PATTERN
	rcall PILIH_KEDIP
	ldi r22, 0
	out TCNT0,r22
	reti

PILIH_KEDIP:
	cpi pattern, 0b11111111
	breq KEDIP8
	cpi pattern, 0b01111111
	breq KEDIP7
	cpi pattern, 0b00111111
	breq KEDIP6
	cpi pattern, 0b00011111
	breq KEDIP5
	cpi pattern, 0b00001111
	breq KEDIP4
	cpi pattern, 0b00000111
	breq KEDIP3
	cpi pattern, 0b00000011
	breq KEDIP2
	cpi pattern, 0b00000001
	breq KEDIP1
	ret

KEDIP8:
	ldi r16, 0b01111111
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

KEDIP7:
	ldi r16, 0b00111111
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

KEDIP6:
	ldi r16, 0b00011111
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

KEDIP5:
	ldi r16, 0b00001111
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

KEDIP4:
	ldi r16, 0b00000111
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

MAU_UBAH_PATTERN:
	rjmp UBAH_PATTERN

KEDIP3:
	ldi r16, 0b00000011
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

KEDIP2:
	ldi r16, 0b00000001
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

KEDIP1:
	ldi r16, 0b00000000
	out PORTC, r16
	rcall DELAY_00
	out PORTC, pattern
	rcall DELAY_00
	ret

UBAH_PATTERN:
	ldi counter, 8
	push r16
	in r16,SREG
	push r16
	lsr pattern		; ubah pattern
	mov r16, pattern
	out PORTC, r16
	rcall DELAY_00
	pop r16
	out SREG,r16
	pop r16
	out TCNT0,r22
	reti

DELAY_00:
	; Generated by delay loop calculator
	; at http://www.bretmulvey.com/avrdelay.html
	;
	; Delay 4 000 cycles
	; 500us at 8.0 MHz
	    ldi  r18, 208
	    ldi  r19, 202
	L0: dec  r19
	    brne L0
	    dec  r18
	    brne L0
	ret
